create table cidade (estado_id bigint not null, id bigint not null auto_increment, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table cliente (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(60) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null, primary key (grupo_id, permissao_id)) engine=InnoDB;
create table item_pedido (preco_total decimal(38,2), preco_unitario decimal(38,2) not null, id bigint not null auto_increment, pedido_id bigint not null, produto_id bigint not null, quantidade bigint not null, observacao varchar(255), primary key (id)) engine=InnoDB;
create table pedido (subtotal decimal(38,2) not null, taxa_frete decimal(38,2) not null, valor_total decimal(38,2) not null, data_cancelamento datetime(6), data_confirmacao datetime(6), data_criacao datetime(6) not null, data_entrega datetime(6), endereco_cep varchar(8), endereco_cidade_id bigint, forma_pagamento_id bigint not null, id bigint not null auto_increment, restaurante_id bigint not null, usuario_cliente_id bigint not null, endereco_numero varchar(20), endereco_complemento varchar(30), endereco_bairro varchar(60), endereco_logradouro varchar(80), status enum ('CANCELADO','CONFIRMADO','CRIADO','ENTREGUE') not null, primary key (id)) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(60) not null, nome varchar(60) not null, primary key (id)) engine=InnoDB;
create table produto (ativo bit, preco decimal(38,2), id bigint not null auto_increment, restaurante_id bigint not null, nome varchar(60), descricao varchar(255), primary key (id)) engine=InnoDB;
create table restaurante (aberto bit, ativo bit, taxa_frete decimal(38,2) not null, cozinha_id bigint not null, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_cep varchar(8), endereco_cidade_id bigint, id bigint not null auto_increment, endereco_numero varchar(20), endereco_complemento varchar(30), endereco_bairro varchar(60), nome varchar(60) not null, endereco_logradouro varchar(80), primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (forma_pagamento_id bigint not null, restaurante_id bigint not null, primary key (forma_pagamento_id, restaurante_id)) engine=InnoDB;
create table restaurante_usuario_responsavel (restaurante_id bigint not null, usuario_id bigint not null, primary key (restaurante_id, usuario_id)) engine=InnoDB;
create table usuario (data_cadastro datetime not null, id bigint not null auto_increment, email varchar(60) not null, nome varchar(60) not null, senha varchar(60) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (grupo_id bigint not null, usuario_id bigint not null, primary key (grupo_id, usuario_id)) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint permissao_grupo_permissao_fk foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint grupo_grupo_permissao_fk foreign key (grupo_id) references grupo (id);
alter table item_pedido add constraint pedido_item_fk foreign key (pedido_id) references pedido (id);
alter table item_pedido add constraint item_pedido_produto_fk foreign key (produto_id) references produto (id);
alter table pedido add constraint pedido_usuario_fk foreign key (usuario_cliente_id) references usuario (id);
alter table pedido add constraint FKk987vfg9cpgx7qxj3166fdqig foreign key (endereco_cidade_id) references cidade (id);
alter table pedido add constraint pedido_forma_pagamento_fk foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table pedido add constraint pedido_restaurante_fk foreign key (restaurante_id) references restaurante (id);
alter table produto add constraint produto_restaurante_fk foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint restaurante_cozinha_fk foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table restaurante_usuario_responsavel add constraint usuario_fk foreign key (usuario_id) references usuario (id);
alter table restaurante_usuario_responsavel add constraint restaurante_fk foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint usuario_grupo_fk foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint usuario_usuario_grupo_fk foreign key (usuario_id) references usuario (id);
